# Embebe recursivamente los archivos de un directorio web como arrays de bytes.
# Sin dependencias externas: solo file(READ ... HEX).
#
# - Incluido desde CMakeLists.txt: define la función, no ejecuta nada.
# - Ejecutado con `cmake -DWEB_DIR=... -DOUT_CPP=... -P este_archivo`: genera el .cpp.

function(embed_web_assets WEB_DIR OUT_CPP)
  file(GLOB_RECURSE _files RELATIVE "${WEB_DIR}" "${WEB_DIR}/*")
  list(SORT _files)

  set(_cpp "// Auto-generated by cmake/embed_assets.cmake. DO NOT EDIT.\n")
  string(APPEND _cpp "#include \"core/assets.h\"\n\n")
  set(_entries "")

  foreach(_f ${_files})
    if(IS_DIRECTORY "${WEB_DIR}/${_f}")
      continue()
    endif()
    file(READ "${WEB_DIR}/${_f}" _hex HEX)
    string(REGEX REPLACE "(..)" "0x\\1," _bytes "${_hex}")
    string(REGEX REPLACE "[^A-Za-z0-9_]" "_" _sym "${_f}")
    string(APPEND _cpp "static const unsigned char asset_${_sym}[] = {${_bytes}};\n")
    string(APPEND _entries "    {\"/${_f}\", asset_${_sym}, sizeof(asset_${_sym})},\n")
  endforeach()

  string(APPEND _cpp
    "\nnamespace assetshrink {\nconst std::vector<Asset>& get_assets() {\n"
    "  static const std::vector<Asset> kAssets = {\n")
  string(APPEND _cpp "${_entries}")
  string(APPEND _cpp "  };\n  return kAssets;\n}\n}  // namespace assetshrink\n")

  file(WRITE "${OUT_CPP}" "${_cpp}")
endfunction()

if(CMAKE_SCRIPT_MODE_FILE AND DEFINED WEB_DIR AND DEFINED OUT_CPP)
  embed_web_assets("${WEB_DIR}" "${OUT_CPP}")
endif()
